/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Supplier.Finance;

import Business.Enterprise.Supplier;
import Business.Organization.Amazon.Admin.WorkQueue;
import Business.Organization.Amazon.Admin.WorkRequest;
import Business.Organization.Supplier.Finance.SupplierFinanceOrganization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manish Gajare
 */
public class SupplierFinanceEmployeeWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    SupplierFinanceOrganization financeOrganization;
    WorkQueue workQueue;
    Supplier supplier;
    
    /**
     * Creates new form SupplierFinanceEmployeeWorkAreaJPanel
     */
    public SupplierFinanceEmployeeWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SupplierFinanceOrganization financeOrganization,WorkQueue workQueue,Supplier supplier) {
        initComponents();
    
    this.userProcessContainer = userProcessContainer;
    this.account = account;
    this.financeOrganization = financeOrganization;
    this.workQueue = workQueue;
    this.supplier = supplier;
   
    populateOrderProcessJTable();
    
    approveJButton.setEnabled(false);
    
    
    }
    
    
    public void populateOrderProcessJTable(){
        
        
        int rowCount = orderProcessjTable.getRowCount();
        for(int i=rowCount-1; i>=0; i--){
            ((DefaultTableModel)orderProcessjTable.getModel()).removeRow(i);
        }
        
        for(WorkRequest workRequest:workQueue.getWorkQueue()){
            
            if(workRequest.getPayment().getInvoice().getOrderItem().get(0).getSupplier().equals(supplier)){
               
                
                
                Object row[] = new Object[7];
                row[0] = workRequest;
                row[1] = workRequest.getPayment().getInvoice().getStatus();
                row[2] = workRequest.getStatus();
                row[3] = workRequest.getBeginningTime().getTime().toString();
                row[4] = workRequest.getToBeDeliveredBy().getTime().toString();
                //row[4] = "?";
                
                if(workRequest.getEndingTime()==null)
                    row[5] = "Not Delivered Yet";
                else    
                    row[5] = workRequest.getEndingTime().getTime().toString();
                
                if(workRequest.getPenalized()==null)
                    row[6] = "---";
                else    
                    row[6] = workRequest.getPenalized();
                

            ((DefaultTableModel)orderProcessjTable.getModel()).addRow(row);
                
                
            }
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderProcessjTable = new javax.swing.JTable();
        orderedItemsJLabel = new javax.swing.JLabel();
        orderedItemsValueJLabel = new javax.swing.JLabel();
        shippingAddressJLabel = new javax.swing.JLabel();
        shippingAddressValueJLabel = new javax.swing.JLabel();
        approveJButton = new javax.swing.JButton();
        amountJLabel = new javax.swing.JLabel();
        amountValueJLabel = new javax.swing.JLabel();

        orderProcessjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Invoice ID", "Payment Status", "Order Status", "Ordered on", "To be Delivered by", "Delivered on", "Penalized?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderProcessjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderProcessjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(orderProcessjTable);

        orderedItemsJLabel.setText("Ordered Items:");

        orderedItemsValueJLabel.setBackground(new java.awt.Color(204, 204, 204));
        orderedItemsValueJLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        shippingAddressJLabel.setText("Shipping Address:");

        shippingAddressValueJLabel.setBackground(new java.awt.Color(204, 204, 204));
        shippingAddressValueJLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        approveJButton.setText("Approve");
        approveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJButtonActionPerformed(evt);
            }
        });

        amountJLabel.setText("Amount:");

        amountValueJLabel.setBackground(new java.awt.Color(204, 204, 204));
        amountValueJLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shippingAddressJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(shippingAddressValueJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(orderedItemsJLabel)
                                .addGap(32, 32, 32)
                                .addComponent(orderedItemsValueJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(amountJLabel)
                                .addGap(63, 63, 63)
                                .addComponent(amountValueJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(506, 506, 506)
                .addComponent(approveJButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(orderedItemsJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(orderedItemsValueJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amountJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addComponent(amountValueJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shippingAddressJLabel)
                    .addComponent(shippingAddressValueJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(approveJButton)
                .addGap(318, 318, 318))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderProcessjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderProcessjTableMouseClicked

     WorkRequest wr = (WorkRequest)orderProcessjTable.getValueAt(orderProcessjTable.getSelectedRow(), 0);
        
     if(wr.getStatus().equals(WorkRequest.ORDER_PLACED))
     approveJButton.setEnabled(true);
     
        String orderedItems="";
        
        for(int i=0;i<wr.getPayment().getInvoice().getOrderItem().size();i++){
            orderedItems = orderedItems+"  "+wr.getPayment().getInvoice().getOrderItem().get(i).getProduct().getName()+" - "+wr.getPayment().getInvoice().getOrderItem().get(i).getQuantity()+"  ";
           
        }

     
     orderedItemsValueJLabel.setText(orderedItems);
     amountValueJLabel.setText(String.valueOf(wr.getPayment().getInvoice().getAmount()));
     shippingAddressValueJLabel.setText(wr.getPayment().getInvoice().getShippingAddress());
     
        
    }//GEN-LAST:event_orderProcessjTableMouseClicked

    private void approveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJButtonActionPerformed

        
     WorkRequest wr = (WorkRequest)orderProcessjTable.getValueAt(orderProcessjTable.getSelectedRow(), 0);
     wr.setStatus(WorkRequest.UNDER_PROCESS);
     wr.setFinance(account);
     populateOrderProcessJTable();
        approveJButton.setEnabled(false);
        
    }//GEN-LAST:event_approveJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountJLabel;
    private javax.swing.JLabel amountValueJLabel;
    private javax.swing.JButton approveJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderProcessjTable;
    private javax.swing.JLabel orderedItemsJLabel;
    private javax.swing.JLabel orderedItemsValueJLabel;
    private javax.swing.JLabel shippingAddressJLabel;
    private javax.swing.JLabel shippingAddressValueJLabel;
    // End of variables declaration//GEN-END:variables
}
