/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Supplier.Shipment;

import Business.Enterprise.Supplier;
import Business.Organization.Amazon.Admin.WorkQueue;
import Business.Organization.Amazon.Admin.WorkRequest;
import Business.Organization.Supplier.Sales.SupplierSalesOrganization;
import Business.Organization.Supplier.Shipment.SupplierShipmentOrganization;
import Business.UserAccount.UserAccount;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Manish Gajare
 */
public class SupplierShipmentEmployeeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierShipmentEmployeeWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount account;
    SupplierShipmentOrganization shipmentOrganization;
    WorkQueue workQueue;
    Supplier supplier;
    
    public SupplierShipmentEmployeeWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SupplierShipmentOrganization shipmentOrganization, WorkQueue workQueue, Supplier supplier) {
        initComponents();
        
        
    this.userProcessContainer = userProcessContainer;
    this.account = account;
    this.shipmentOrganization = shipmentOrganization;
    this.workQueue = workQueue;
    this.supplier = supplier;
   
    assignJButton.setEnabled(false);
    orderDeliveredJButton.setEnabled(false);
    confirmationNumberJTextField.setEnabled(false);
    
    populateOrderProcessJTable();
        
            
    }
    
    public void populateOrderProcessJTable(){
        
        
        int rowCount = orderProcessjTable.getRowCount();
        for(int i=rowCount-1; i>=0; i--){
            ((DefaultTableModel)orderProcessjTable.getModel()).removeRow(i);
        }
        
        for(WorkRequest workRequest:workQueue.getWorkQueue()){
            
            if(workRequest.getPayment().getInvoice().getOrderItem().get(0).getSupplier().equals(supplier)){
               
                
                
                Object row[] = new Object[7];
                row[0] = workRequest;
                row[1] = workRequest.getPayment().getInvoice().getStatus();
                row[2] = workRequest.getStatus();
                row[3] = workRequest.getBeginningTime().getTime().toString();
                row[4] = workRequest.getToBeDeliveredBy().getTime().toString();
                
                
                if(workRequest.getEndingTime()==null)
                    row[5] = "Not Delivered Yet";
                else    
                    row[5] = workRequest.getEndingTime().getTime().toString();
                
                if(workRequest.getPenalized()==null)
                    row[6] = "---";
                else    
                    row[6] = workRequest.getPenalized();
                

            ((DefaultTableModel)orderProcessjTable.getModel()).addRow(row);
                
                
            }
            
        }
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountValueJLabel = new javax.swing.JLabel();
        orderedItemsValueJLabel = new javax.swing.JLabel();
        orderedItemsJLabel = new javax.swing.JLabel();
        shippingAddressValueJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderProcessjTable = new javax.swing.JTable();
        orderDeliveredJButton = new javax.swing.JButton();
        assignJButton = new javax.swing.JButton();
        amountJLabel = new javax.swing.JLabel();
        shippingAddressJLabel = new javax.swing.JLabel();
        confirmationNumberJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        amountValueJLabel.setBackground(new java.awt.Color(204, 204, 204));
        amountValueJLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        orderedItemsValueJLabel.setBackground(new java.awt.Color(204, 204, 204));
        orderedItemsValueJLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        orderedItemsJLabel.setText("Ordered Items:");

        shippingAddressValueJLabel.setBackground(new java.awt.Color(204, 204, 204));
        shippingAddressValueJLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        orderProcessjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Invoice ID", "Payment Status", "Order Status", "Ordered on", "To be Delivered by", "Delivered on", "Penalized?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderProcessjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderProcessjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(orderProcessjTable);

        orderDeliveredJButton.setText("Order Delivered");
        orderDeliveredJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDeliveredJButtonActionPerformed(evt);
            }
        });

        assignJButton.setText("Assign");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        amountJLabel.setText("Amount:");

        shippingAddressJLabel.setText("Shipping Address:");

        confirmationNumberJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmationNumberJTextFieldActionPerformed(evt);
            }
        });
        confirmationNumberJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                confirmationNumberJTextFieldKeyTyped(evt);
            }
        });

        jLabel1.setText("Confirmation Number: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shippingAddressJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(shippingAddressValueJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(orderedItemsJLabel)
                                .addGap(32, 32, 32)
                                .addComponent(orderedItemsValueJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(amountJLabel)
                                .addGap(63, 63, 63)
                                .addComponent(amountValueJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(assignJButton)
                        .addGap(179, 179, 179)
                        .addComponent(orderDeliveredJButton)
                        .addGap(396, 396, 396))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmationNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(306, 306, 306))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(orderedItemsJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(orderedItemsValueJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amountJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addComponent(amountValueJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shippingAddressJLabel)
                    .addComponent(shippingAddressValueJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmationNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderDeliveredJButton)
                    .addComponent(assignJButton))
                .addGap(292, 292, 292))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderProcessjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderProcessjTableMouseClicked

        WorkRequest wr = (WorkRequest)orderProcessjTable.getValueAt(orderProcessjTable.getSelectedRow(), 0);

        if(wr.getStatus().equals(WorkRequest.PACKAGING_DONE)){
            assignJButton.setEnabled(true);
            orderDeliveredJButton.setEnabled(false);
            confirmationNumberJTextField.setEnabled(false);
        }else if(wr.getStatus().equals(WorkRequest.SHIPPING_PROCESS)){
            assignJButton.setEnabled(false);
            orderDeliveredJButton.setEnabled(true);
            confirmationNumberJTextField.setEnabled(true);
        }

       String orderedItems="";
        
        for(int i=0;i<wr.getPayment().getInvoice().getOrderItem().size();i++){
            orderedItems = orderedItems+"  "+wr.getPayment().getInvoice().getOrderItem().get(i).getProduct().getName()+" - "+wr.getPayment().getInvoice().getOrderItem().get(i).getQuantity()+"  ";
           
        }

        orderedItemsValueJLabel.setText(orderedItems);
        amountValueJLabel.setText(String.valueOf(wr.getPayment().getInvoice().getAmount()));
        shippingAddressValueJLabel.setText(wr.getPayment().getInvoice().getShippingAddress());
    }//GEN-LAST:event_orderProcessjTableMouseClicked

    private void orderDeliveredJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDeliveredJButtonActionPerformed

    int count = 0;
       if( confirmationNumberJTextField.getText().isEmpty() ){ 
     count++;
       }
        
       if(count==0){    
        
        WorkRequest wr = (WorkRequest)orderProcessjTable.getValueAt(orderProcessjTable.getSelectedRow(), 0);
        
        System.out.println(wr.getPayment().getConfirmationNumber());
        
        if(wr.getPayment().getConfirmationNumber()==Integer.parseInt(confirmationNumberJTextField.getText())){
        
        wr.setStatus(WorkRequest.SHIPPING_DONE);
        wr.setShipped(account);   
        
        Calendar cal = Calendar.getInstance();

        wr.setEndingTime(cal);
        
        if(wr.getEndingTime().before(wr.getToBeDeliveredBy())){
            
            wr.setPenalized("No");
            
            wr.getPayment().getInvoice().setStatus("paid");
            
            
            
            
        } else{
            
           double previousAmountForSupplier = wr.getPayment().getInvoice().getAmount();
            
            wr.getPayment().getInvoice().setAmount(previousAmountForSupplier*0.8);
            
            wr.setPenalized("Yes - "+previousAmountForSupplier*0.2);
            
            wr.getPayment().getInvoice().setStatus("paid"); 
            
            
        }
        
        
        
        
        
        }
        
        
        
        populateOrderProcessJTable();
        orderDeliveredJButton.setEnabled(false);
        confirmationNumberJTextField.setEnabled(false);
        
        
       }
       else{
           
           JOptionPane.showMessageDialog(null, "Please fill required field");
           
       }
        
        
        
        

    }//GEN-LAST:event_orderDeliveredJButtonActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        WorkRequest wr = (WorkRequest)orderProcessjTable.getValueAt(orderProcessjTable.getSelectedRow(), 0);
        wr.setStatus(WorkRequest.SHIPPING_PROCESS);
        wr.setShippingProcess(account);
        populateOrderProcessJTable();
        assignJButton.setEnabled(false);

    }//GEN-LAST:event_assignJButtonActionPerformed

    private void confirmationNumberJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmationNumberJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmationNumberJTextFieldActionPerformed

    private void confirmationNumberJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmationNumberJTextFieldKeyTyped
       
       char c =evt.getKeyChar();
       if(!(Character.isDigit(c) || (c== KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)) ){
           evt.consume();
       }   
        
        
    }//GEN-LAST:event_confirmationNumberJTextFieldKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountJLabel;
    private javax.swing.JLabel amountValueJLabel;
    private javax.swing.JButton assignJButton;
    private javax.swing.JTextField confirmationNumberJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton orderDeliveredJButton;
    private javax.swing.JTable orderProcessjTable;
    private javax.swing.JLabel orderedItemsJLabel;
    private javax.swing.JLabel orderedItemsValueJLabel;
    private javax.swing.JLabel shippingAddressJLabel;
    private javax.swing.JLabel shippingAddressValueJLabel;
    // End of variables declaration//GEN-END:variables
}
