/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.System;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.System.SystemAdminOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Manish Gajare
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    DB4OUtil db4OUtil;
    UserAccount account;
    SystemAdminOrganization systemAdminOrganization;
    
    
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SystemAdminOrganization systemAdminOrganization, Enterprise enterprise, EcoSystem system,DB4OUtil db4OUtil) {
        initComponents();
        
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.db4OUtil = db4OUtil;
        this.account = account;
        this.systemAdminOrganization = systemAdminOrganization;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageAllJButton = new javax.swing.JButton();

        jLabel1.setText("System Admin Work Area");

        manageAllJButton.setText("Manage All");
        manageAllJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAllJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(manageAllJButton)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(manageAllJButton)
                .addContainerGap(196, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAllJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAllJButtonActionPerformed

        
        ManageAllJPanel majp = new ManageAllJPanel(userProcessContainer,account,systemAdminOrganization,enterprise,system,db4OUtil);
        userProcessContainer.add("ManageAllJPanel", majp);
        
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);    
  
        
        
    }//GEN-LAST:event_manageAllJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAllJButton;
    // End of variables declaration//GEN-END:variables
}
