/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Supplier.Inventory;

import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Supplier;
import Business.Organization.Amazon.Inventory.ProductCatalogList;
import Business.Organization.Supplier.Inventory.SupplierInventoryOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Manish Gajare
 */
public class SupplierInventoryEmployeeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierInventoryEmployeeWorkAreaJPanel
     */
    
    JPanel userProcessContainer; 
    UserAccount account; 
    SupplierInventoryOrganization inventoryOrganization;
    ProductCatalogList productCatalogList;
    DB4OUtil db4OUtil;
    Supplier enterprise;
    
    public SupplierInventoryEmployeeWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SupplierInventoryOrganization inventoryOrganization,ProductCatalogList productCatalogList, DB4OUtil db4OUtil,Supplier enterprise) {
        initComponents();
        
    this.userProcessContainer = userProcessContainer; 
    this.account = account; 
    this.inventoryOrganization = inventoryOrganization;
    this.productCatalogList = productCatalogList;
    this.db4OUtil = db4OUtil;    
    this.enterprise = enterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageProductsJButton = new javax.swing.JButton();

        jLabel1.setText("Supplier Inventory Employee Work Area");

        manageProductsJButton.setText("Manage Products");
        manageProductsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(227, 227, 227))
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(manageProductsJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(manageProductsJButton)
                .addContainerGap(336, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageProductsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductsJButtonActionPerformed

        
        ManageProductCatalogJPanel mpcjp = new ManageProductCatalogJPanel(userProcessContainer,account,inventoryOrganization,productCatalogList,db4OUtil,enterprise);
        userProcessContainer.add("ManageProductCatalogJPanel", mpcjp);
        
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);    
        
        
    }//GEN-LAST:event_manageProductsJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageProductsJButton;
    // End of variables declaration//GEN-END:variables
}
