/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer.CustomerSignUp;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Amazon;
import Business.Enterprise.Enterprise;
import Business.Network.CountryNetwork;
import Business.Network.RegionNetwork;
import Business.Network.StateNetwork;
import Business.Customer.Customer;
import Business.Customer.CustomerAccount;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Manish Gajare
 */
public class SignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    DB4OUtil db4OUtil;


    public SignUpJPanel(JPanel userProcessContainer, EcoSystem system, DB4OUtil db4OUtil) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.db4OUtil = db4OUtil;

        populateCountryJComboBox();

    }

    private void populateCountryJComboBox() {

        ArrayList<CountryNetwork> countryNetworkList = system.getCountryNetworkList();

        countryJComboBox.removeAllItems();


        for (int i = 0; countryNetworkList.size() > i; i++) {
            countryJComboBox.addItem(countryNetworkList.get(i));
        }

    }

    private void populateStateJComboBox(CountryNetwork country) {

        stateJComboBox.removeAllItems();
        ArrayList<StateNetwork> stateNetworkList = country.getStateNetworkList();


        for (int i = 0; stateNetworkList.size() > i; i++) {
            stateJComboBox.addItem(stateNetworkList.get(i));
        }

    }

    private void populateRegionJComboBox(StateNetwork state) {

        regionJComboBox.removeAllItems();
        ArrayList<RegionNetwork> regionNetworkList = state.getRegionNetworkList();

        for (int i = 0; regionNetworkList.size() > i; i++) {
            regionJComboBox.addItem(regionNetworkList.get(i));
        }

    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        usernameJTextField = new javax.swing.JTextField();
        passwordJTextField = new javax.swing.JTextField();
        countryJComboBox = new javax.swing.JComboBox();
        stateJComboBox = new javax.swing.JComboBox();
        regionJComboBox = new javax.swing.JComboBox();
        signUpJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        phoneNoJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emailIdJTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Sign Up");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 70, -1, -1));

        jLabel2.setText("Country :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jLabel3.setText("State :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jLabel4.setText("Region :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jLabel5.setText("Name :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel6.setText("Username :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel7.setText("Password :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        nameJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameJTextFieldKeyTyped(evt);
            }
        });
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 125, -1));

        usernameJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameJTextFieldKeyTyped(evt);
            }
        });
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 126, -1));

        passwordJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordJTextFieldKeyTyped(evt);
            }
        });
        add(passwordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 126, -1));

        countryJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryJComboBoxActionPerformed(evt);
            }
        });
        add(countryJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 129, -1));

        stateJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateJComboBoxActionPerformed(evt);
            }
        });
        add(stateJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 129, -1));

        add(regionJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 129, -1));

        signUpJButton.setText("Sign Up");
        signUpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpJButtonActionPerformed(evt);
            }
        });
        add(signUpJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        jLabel8.setText("Phone No. :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        phoneNoJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNoJTextFieldKeyTyped(evt);
            }
        });
        add(phoneNoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 125, -1));

        jLabel9.setText("Email ID :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        emailIdJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailIdJTextFieldKeyTyped(evt);
            }
        });
        add(emailIdJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 126, -1));

        jButton1.setText("<< BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void countryJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryJComboBoxActionPerformed
       CountryNetwork country = (CountryNetwork) countryJComboBox.getSelectedItem();
        if (country != null) {
            populateStateJComboBox(country);
        }

    }//GEN-LAST:event_countryJComboBoxActionPerformed

    private void stateJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateJComboBoxActionPerformed

        StateNetwork state = (StateNetwork) stateJComboBox.getSelectedItem();
        if (state != null) {
            populateRegionJComboBox(state);
        }
        
    }//GEN-LAST:event_stateJComboBoxActionPerformed

    private void signUpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpJButtonActionPerformed

        int count = 0;
       if( nameJTextField.getText().isEmpty() || phoneNoJTextField.getText().isEmpty() || emailIdJTextField.getText().isEmpty() || passwordJTextField.getText().isEmpty() || usernameJTextField.getText().isEmpty() ){ 
     count++;
       }
        
       if(count==0){
                            // Get user name
        String userName = usernameJTextField.getText();
        // Get Password
        String password = String.valueOf(passwordJTextField.getText());

        //Step1: Check in the EcoSystem
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        //Step2: If user account is not in the system's user account directory
        
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
    
        
        
        String countryName = null;
        if (userAccount == null) {
//            1
            
            
            
            
            
            for (CountryNetwork countryNetwork : system.getCountryNetworkList()) {
//              2  
            countryName = countryNetwork.getCountryName();
                
                for (StateNetwork stateNetwork : countryNetwork.getStateNetworkList()) {
//              3  
        
                
                for (RegionNetwork regionNetwork : stateNetwork.getRegionNetworkList()) {
//              4  
                    
                    
                    
                for (Enterprise enterprise : regionNetwork.getEnterpriseDirectory().getEnterpriseList()) {
//               5     
                    
                 
                    
                    if (enterprise.getUserAccountDirectory().authenticateUser(userName, password) != null) {
                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                        inEnterprise = enterprise;
                        
                    }else{
                        
                        
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                           
                            userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                                if(userAccount!=null){
                                    inEnterprise = enterprise;
                                    inOrganization = organization;
                                   break;
                                    
                                    }
                            
                            }
                   
                        
                    } 
                    
               if (inEnterprise != null) {
                        break;
                    }
                   
               
                
                
         //       5  
                }
                
                if (inEnterprise != null) {
                        break;
                    }
                
                
           
                
        //           4     
                    }
        
                  
                
     //           3     
                }
                
                     
                
//           2     
            }
            
                   
        
 //    1       
        }
        

       
        
        
        
        
        
        CustomerAccount customerAccount=null;
       Amazon amazon = null; 
      if (userAccount == null && customerAccount==null) {
//            1
            
            
            
            for (CountryNetwork countryNetwork : system.getCountryNetworkList()) {
//              2  
            countryName = countryNetwork.getCountryName();
                
                for (StateNetwork stateNetwork : countryNetwork.getStateNetworkList()) {
//              3  
        
                
                for (RegionNetwork regionNetwork : stateNetwork.getRegionNetworkList()) {
//              4  
                    
                    
                    
                for (Enterprise enterprise : regionNetwork.getEnterpriseDirectory().getEnterpriseList()) {
//               5     
      
                    
                    
                 
          if(enterprise instanceof Amazon){
           amazon = (Amazon)enterprise;
              
           inEnterprise = amazon;
           

           if(amazon.getCustomerAccountDirectory().authenticateCustomer(userName, password)!=null){
               
           customerAccount = amazon.getCustomerAccountDirectory().authenticateCustomer(userName, password);
           
           break;
             }      
          
           
        }          
                    
               
                   
               
                
                
         //       5  
                }
                
                if(inEnterprise!=null)
                    break;
                 
           
                
        //           4     
                    }
        
                if(inEnterprise!=null)
                    break;
                 
                
     //           3     
                }
                
                if(inEnterprise!=null)
                    break;
                 
                
//           2     
            }
            
            
        
 //    1       
        }
          
//.............................................................................................
      
   
      
      
      
      
      
      
      
      
ArrayList<CountryNetwork> countryNetworkList = system.getCountryNetworkList();
        Amazon amazonEnterprise = null; 
        
        for(int i=0;i<countryNetworkList.size();i++){
        
       try {
        if(countryNetworkList.get(i).getCountryName().equals(countryName))    
        {
        ArrayList<StateNetwork> stateNetworkList = countryNetworkList.get(i).getStateNetworkList();
        
        
        for(int j=0;j<stateNetworkList.size();j++){
        
       
        ArrayList<RegionNetwork> regionNetworkList = stateNetworkList.get(j).getRegionNetworkList();
        
        
        
        
        for(int k=0;k<regionNetworkList.size();k++){
        
        
        
      ArrayList<Enterprise> enterpriseList = regionNetworkList.get(k).getEnterpriseDirectory().getEnterpriseList();  
        
       
      for(int l=0;l<enterpriseList.size();l++){
        
          if(enterpriseList.get(l) instanceof Amazon){
             amazonEnterprise = (Amazon)enterpriseList.get(l);
             
          
        }
        
      

      
   
        
        }
        
        }
        
        

        
        
        
        
        
        }
        

        
        }
        
       } catch (NullPointerException e){}
        
        }
              
      
      
      
      
      
      
      
      
      
        

           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
           
      if (userAccount == null && customerAccount==null) {     
              amazon=null;
countryNetworkList = system.getCountryNetworkList();

        
        for(int i=0;i<countryNetworkList.size();i++){
        
    
        if(countryNetworkList.get(i).getCountryName().equals(countryJComboBox.getSelectedItem().toString()))    
        {
        ArrayList<StateNetwork> stateNetworkList = countryNetworkList.get(i).getStateNetworkList();

        
        for(int j=0;j<stateNetworkList.size();j++){
        
       
        ArrayList<RegionNetwork> regionNetworkList = stateNetworkList.get(j).getRegionNetworkList();

        
        
        
        for(int k=0;k<regionNetworkList.size();k++){
        
        
        
      ArrayList<Enterprise> enterpriseList = regionNetworkList.get(k).getEnterpriseDirectory().getEnterpriseList();  

       
      for(int l=0;l<enterpriseList.size();l++){
          
          if(enterpriseList.get(l) instanceof Amazon){
           amazon = (Amazon)enterpriseList.get(l);
              
           
           
           
        }
          
          
          
        
      
   
        
        }
        
        }
        
        

        
        
        
        
        
        }
        

        
        }
        
        
        
        }
    
        System.out.println(amazon);
        
      Customer customer = amazon.getCustomerDirectory().createCustomer(nameJTextField.getText(), phoneNoJTextField.getText(), emailIdJTextField.getText(), countryJComboBox.getSelectedItem().toString(), stateJComboBox.getSelectedItem().toString(), regionJComboBox.getSelectedItem().toString());
      amazon.getCustomerAccountDirectory().createCustomerAccount(usernameJTextField.getText(), passwordJTextField.getText(), customer);
       
       db4OUtil.storeSystem(system);
       
       nameJTextField.setText(null);
       emailIdJTextField.setText(null);
       phoneNoJTextField.setText(null);
       usernameJTextField.setText(null);
       passwordJTextField.setText(null);
       countryJComboBox.setSelectedItem(null);
     
      }
      
      else{
          
          
          JOptionPane.showMessageDialog(null, "Please use Different Username. Username already used.");
          
          
      }
      
      
      
      
           
       }
       else{
       
           JOptionPane.showMessageDialog(null, "Please fill all the fields");
           
       }
       
    }//GEN-LAST:event_signUpJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameJTextFieldKeyTyped
       
                                    
       char c =evt.getKeyChar();
       if(!(Character.isAlphabetic(c) || (c== KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)) ){
           evt.consume();
       }
  
        
       
    }//GEN-LAST:event_nameJTextFieldKeyTyped

    private void phoneNoJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNoJTextFieldKeyTyped
       
     char c =evt.getKeyChar();
       if(!(Character.isDigit(c) || (c== KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)) ){
           evt.consume();
       }   
        
        
    }//GEN-LAST:event_phoneNoJTextFieldKeyTyped

    private void emailIdJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailIdJTextFieldKeyTyped
        
        

   
        char c =evt.getKeyChar();
       if(((c==KeyEvent.VK_SPACE) ) ){
           evt.consume();
       }
       
       
    }//GEN-LAST:event_emailIdJTextFieldKeyTyped

    private void usernameJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameJTextFieldKeyTyped
        
        
        char c =evt.getKeyChar();
       if(((c==KeyEvent.VK_SPACE) ) ){
           evt.consume();
       }
        
        
    }//GEN-LAST:event_usernameJTextFieldKeyTyped

    private void passwordJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordJTextFieldKeyTyped

        
       char c =evt.getKeyChar();
       if(((c==KeyEvent.VK_SPACE) ) ){
           evt.consume();
       }
        
    }//GEN-LAST:event_passwordJTextFieldKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox countryJComboBox;
    private javax.swing.JTextField emailIdJTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField passwordJTextField;
    private javax.swing.JTextField phoneNoJTextField;
    private javax.swing.JComboBox regionJComboBox;
    private javax.swing.JButton signUpJButton;
    private javax.swing.JComboBox stateJComboBox;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
